### ISSUE TITLE
Intellij 2018.1.3  Attempt to modify PSI for non-committed Document!

### ISSUE THREAD

**Issue by philero** [dubreuia/intellij-plugin-save-actions#152]
An error occured with last intelliJ version of plugin...

IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
Subscription is active until December 19, 2018
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

See the stacktrace :

Attempt to modify PSI for non-committed Document!
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:348)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:143)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:155)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:613)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:712)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:67)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:481)
	at com.intellij.psi.impl.source.tree.java.ModifierListElement.addInternal(ModifierListElement.java:45)
	at com.intellij.psi.impl.source.JavaStubPsiElement.addAfter(JavaStubPsiElement.java:92)
	at com.intellij.psi.impl.source.PsiModifierListImpl.addAnnotation(PsiModifierListImpl.java:301)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.addPhysicalAnnotation(AddAnnotationPsiFix.java:173)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.lambda$invoke$0(AddAnnotationPsiFix.java:162)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:256)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:238)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:174)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:214)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:105)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:216)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:172)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:155)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:258)
	at com.intellij.codeInsight.intention.AddAnnotationPsiFix.invoke(AddAnnotationPsiFix.java:159)
	at com.intellij.codeInspection.AnnotateMethodFix.annotateMethod(AnnotateMethodFix.java:114)
	at com.intellij.codeInspection.AnnotateMethodFix.applyFix(AnnotateMethodFix.java:99)
	at com.intellij.codeInspection.AnnotateMethodFix.applyFix(AnnotateMethodFix.java:30)
	at com.dubreuia.processors.java.InspectionProcessor$InspectionWriteQuickFixesAction.writeQuickFixes(InspectionProcessor.java:92)
	at com.dubreuia.processors.java.InspectionProcessor$InspectionWriteQuickFixesAction.run(InspectionProcessor.java:83)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:238)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:174)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:214)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:105)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:216)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:172)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:155)
	at com.dubreuia.processors.java.InspectionProcessor.lambda$run$0(InspectionProcessor.java:49)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dubreuia** [comment]
Duplicate #109
