### ISSUE TITLE
Exception in plugin

### ISSUE THREAD

**Issue by billriess** [dubreuia/intellij-plugin-save-actions#206]
**Describe the bug**
Exception in plugin

**To Reproduce**
Use plugin

**Versions**
PHPStorm 2018.3.3

**Exception Report**
```
Got unexpected exception during formatting PHP file

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Wrong offset: 672. Should be in range: [0, 642]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.checkStop(AbstractLayoutCodeProcessor.java:564)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.performFileProcessing(AbstractLayoutCodeProcessor.java:558)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.lambda$iteration$0(AbstractLayoutCodeProcessor.java:530)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:277)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.iteration(AbstractLayoutCodeProcessor.java:530)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$runProcessFiles$3(AbstractLayoutCodeProcessor.java:383)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:248)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:571)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:454)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:251)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:205)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.runProcessFiles(AbstractLayoutCodeProcessor.java:378)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.run(AbstractLayoutCodeProcessor.java:263)
	at com.dubreuia.processors.RearrangeCodeProcessor.run(RearrangeCodeProcessor.java:74)
	at com.dubreuia.core.component.SaveActionManager.runProcessor(SaveActionManager.java:83)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.dubreuia.core.component.SaveActionManager.processPsiFile(SaveActionManager.java:74)
	at com.dubreuia.core.component.SaveActionManager.processPsiFileIfNecessary(SaveActionManager.java:65)
	at com.dubreuia.core.component.SaveActionManager.beforeDocumentSaving(SaveActionManager.java:55)
	at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy27.beforeDocumentSaving(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:140)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$new$0(FileDocumentManagerImpl.java:120)
	at com.sun.proxy.$Proxy27.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:422)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:402)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:421)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:383)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:106)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:383)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:334)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:324)
	at com.intellij.openapi.vcs.ex.LineStatusTracker$fireFileUnchanged$1.run(LineStatusTracker.kt:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionLater$4(TransactionGuardImpl.java:271)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IndexOutOfBoundsException: Wrong offset: 672. Should be in range: [0, 642]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:172)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1008)
	at com.intellij.psi.codeStyle.arrangement.ArrangementUtil.expandToLineIfPossible(ArrangementUtil.java:144)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.createEntry(PhpArrangementVisitor.java:205)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.createEntry(PhpArrangementVisitor.java:190)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.visitPhpMethod(PhpArrangementVisitor.java:120)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:89)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.processContainerEntry(PhpArrangementVisitor.java:106)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.visitPhpClass(PhpArrangementVisitor.java:94)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.accept(PhpClassImpl.java:532)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.visitPhpGroupStatement(PhpArrangementVisitor.java:69)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:24)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.processContainerEntry(PhpArrangementVisitor.java:106)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.visitPhpNamespace(PhpArrangementVisitor.java:81)
	at com.jetbrains.php.lang.psi.elements.impl.PhpNamespaceImpl.accept(PhpNamespaceImpl.java:105)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.visitPhpGroupStatement(PhpArrangementVisitor.java:69)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:24)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:730)
	at com.jetbrains.php.arrangement.PhpArrangementVisitor.visitPhpFile(PhpArrangementVisitor.java:64)
	at com.jetbrains.php.lang.psi.PhpFileImpl.accept(PhpFileImpl.java:186)
	at com.jetbrains.php.arrangement.PhpRearranger.parse(PhpRearranger.java:269)
	at com.intellij.psi.codeStyle.arrangement.engine.ArrangementEngine$Context.from(ArrangementEngine.java:543)
	at com.intellij.psi.codeStyle.arrangement.engine.ArrangementEngine.arrange(ArrangementEngine.java:133)
	at com.intellij.psi.codeStyle.arrangement.engine.ArrangementEngine.arrange(ArrangementEngine.java:94)
	at com.dubreuia.processors.RearrangeCodeProcessor.lambda$prepareRearrangeCommand$1(RearrangeCodeProcessor.java:62)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.dubreuia.processors.RearrangeCodeProcessor.lambda$prepareTask$0(RearrangeCodeProcessor.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:363)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:264)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:263)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:321)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:323)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:363)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.lambda$performFileProcessing$3(AbstractLayoutCodeProcessor.java:556)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:670)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:683)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ReformatFilesTask.performFileProcessing(AbstractLayoutCodeProcessor.java:556)
	... 83 more
```

**Comment by dubreuia** [comment]
Duplicates #113
