### ISSUE TITLE
group with id "CodeFormatGroup" isn't registered

### ISSUE THREAD

**Issue by knzivid** [dubreuia/intellij-plugin-save-actions#299]
**Describe the bug**
After updating to CLion 2020.1 EAP, the save actions plugin throws an error in startup.

**What triggered the plugin**
Opening the IDE

**Versions**
```
CLion 2020.1 EAP
Build #CL-201.4515.29, built on January 30, 2020
CLion EAP User
Expiration date: February 29, 2020
Runtime version: 11.0.5+9-b674.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.15-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 8179M
Cores: 16
Registry: run.processes.with.pty=TRUE, cidr.max.intellisense.file.length=1500000
Non-Bundled Plugins: com.dubreuia
```

Complete stacktrace

```
com.intellij.diagnostic.PluginException: com.intellij.openapi.actionSystem.DefaultActionGroup (com.dubreuia.core.action.SaveActionsGroup): group with id "CodeFormatGroup" isn't registered; action will be added to the "Other" group [Plugin: com.dubreuia]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:394)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:389)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:909)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:875)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:819)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionsChildElement(ActionManagerImpl.java:1078)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:507)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:158)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:567)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.doGetService(PlatformComponentManagerImpl.kt:343)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:330)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
	at com.jetbrains.cidr.lang.actions.OCActionsManager.componentsInitialized(OCActionsManager.java:12)
	at com.intellij.idea.ApplicationLoader$callAppInitialized$2.run(ApplicationLoader.kt:653)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:225)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:204)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dubreuia** [comment]
Thanks for the issue @knzivid, it seems it works on intellij, same version. I'll look into it.

**Comment by dubreuia** [comment]
@knzivid does the IDE starts anyway?

**Comment by knzivid** [comment]
Yes, it works fine

**Comment by dubreuia** [comment]
Reopen if this issue is still present
