### ISSUE TITLE
There is null pointer exception on Logger information params

### ISSUE THREAD

**Issue by mrust1** [dubreuia/intellij-plugin-save-actions#384]
When I worked on my projects Every time Save actions gives errors. and I investigate for my Save action version. I saw this is only LOGGER.info.

My save Actions' version is '2.2.0'

![image](https://user-images.githubusercontent.com/7836162/137116292-6e6c1030-b705-4ea9-83f5-bc783b11e19f.png)

Error area

```
  List<SimpleEntry<Action, Result<ResultCode>>> results = processorsEligible.stream()
                .peek(command -> LOGGER.info("Execute command " + command + " on " + psiFiles.size() + " files"))
                .map(command -> new SimpleEntry<>(command.getAction(), command.execute()))
                .collect(toList());
  LOGGER.info("Exit engine with results "
                + results.stream()
                .map(entry -> entry.getKey() + ":" + entry.getValue())
                .collect(toList())); 
```
```
java.lang.NullPointerException
	at com.dubreuia.processors.Result.toString(Result.java:49)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at com.dubreuia.core.component.Engine.lambda$processPsiFiles$6(Engine.java:110)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.dubreuia.core.component.Engine.processPsiFiles(Engine.java:111)
	at com.dubreuia.core.component.Engine.processPsiFilesIfNecessary(Engine.java:90)
	at com.dubreuia.core.component.SaveActionManager.guardedProcessPsiFiles(SaveActionManager.java:169)
	at com.dubreuia.core.component.SaveActionManager.lambda$beforeDocumentsSaving$3(SaveActionManager.java:153)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at com.dubreuia.core.component.SaveActionManager.beforeDocumentsSaving(SaveActionManager.java:152)
	at com.dubreuia.core.component.SaveActionManager.beforeAllDocumentsSaving(SaveActionManager.java:137)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:671)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:422)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
```

**Comment by dubreuia** [comment]
https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v2.4.0
