### ISSUE TITLE
not support idea 2021.3.1

### ISSUE THREAD

**Issue by shengulong** [dubreuia/intellij-plugin-save-actions#391]
**Describe the bug**

**What triggered the plugin**
Frame deactivation (window loses focus), CTRL+SHIFT+S, CTRL+S, etc.

**Versions**
In Intellij, go to "Help > About > Copy" and paste it here

**Comment by birnbuazn** [comment]
Experiencing the same problem: Initialisation of the plugin fails at startup sind 2021.3:

```
Plugin 'com.dubreuia' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ExceptionInInitializerError
    at com.dubreuia.core.component.JavaComponent.initComponent(JavaComponent.java:52)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:370)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:370)
    at com.intellij.idea.ApplicationLoader$startApp$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:141)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
    at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
    at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:407)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalStateException: Cannot find inspection tool SerializableHasSerialVersionUIDFieldInspection
    at com.dubreuia.processors.java.inspection.SerializableHasSerialVersionUIDFieldInspectionWrapper.lambda$get$1(SerializableHasSerialVersionUIDFieldInspectionWrapper.java:54)
    at java.base/java.util.Optional.orElseThrow(Optional.java:408)
    at com.dubreuia.processors.java.inspection.SerializableHasSerialVersionUIDFieldInspectionWrapper.get(SerializableHasSerialVersionUIDFieldInspectionWrapper.java:54)
    at com.dubreuia.processors.java.JavaProcessor.<init>(JavaProcessor.java:146)
    at com.dubreuia.processors.java.JavaProcessor.<clinit>(JavaProcessor.java:112)
    ... 40 more
```


**IntelliJ-Version**
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    org.intellij.plugins.hcl (0.7.14)
    net.seesharpsoft.intellij.plugins.csv (2.18.1)
    de.netnexus.camelcaseplugin (3.0.8)
    com.andrey4623.rainbowcsv (2.0)
    String Manipulation (8.22.203.000.1)
    Statistic (4.1.7)
    org.jetbrains.plugins.vue (213.5744.223)
    com.dmarcotte.handlebars (213.5744.190)
    CheckStyle-IDEA (5.58.0)
    org.mapstruct.intellij (1.3.0)
    com.intellij.aspectj (213.5744.125)
    com.haulmont.jpab (5.9-213)
    MavenRunHelper (4.18.212.000.3)

Kotlin: 213-1.5.10-release-949-IJ5744.223

**Comment by MartinX3** [comment]
At least we can use the "format on save" feature now in IntelliJ without this plugin.

https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save

**Comment by sfragata** [comment]
There is a PR for this issue
https://github.com/dubreuia/intellij-plugin-save-actions/pull/387

**Comment by inthink** [comment]
> At least we can use the "format on save" feature now in IntelliJ without this plugin.
> 
> https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save

this not works on my machine

**Comment by inthink** [comment]
> 

this not works on my machine

**Comment by inthink** [comment]
> At least we can use the "format on save" feature now in IntelliJ without this plugin.
> 
> https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save

this not works on my machine

**Comment by MartinX3** [comment]
> > At least we can use the "format on save" feature now in IntelliJ without this plugin.
> > 
> > https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save
> 
> this not works on my machine

You need to read the manual.
Default setting is to only reformat "go" files...

**Comment by sfragata** [comment]
> At least we can use the "format on save" feature now in IntelliJ without this plugin.
> 
> https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save

format on save intelij's feature doesn't work the same way than this plugin that add some features like add "this." to the class attribute, add final keyword tu parameters etc

**Comment by jcaballo** [comment]
Same problem here unfortunately 

```
Plugin 'com.dubreuia' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ExceptionInInitializerError
    at com.dubreuia.core.component.JavaComponent.initComponent(JavaComponent.java:52)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:401)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:370)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:370)
    at com.intellij.idea.ApplicationLoader$startApp$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:141)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
    at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
    at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:407)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalStateException: Cannot find inspection tool SerializableHasSerialVersionUIDFieldInspection
    at com.dubreuia.processors.java.inspection.SerializableHasSerialVersionUIDFieldInspectionWrapper.lambda$get$1(SerializableHasSerialVersionUIDFieldInspectionWrapper.java:54)
    at java.base/java.util.Optional.orElseThrow(Optional.java:408)
    at com.dubreuia.processors.java.inspection.SerializableHasSerialVersionUIDFieldInspectionWrapper.get(SerializableHasSerialVersionUIDFieldInspectionWrapper.java:54)
    at com.dubreuia.processors.java.JavaProcessor.<init>(JavaProcessor.java:146)
    at com.dubreuia.processors.java.JavaProcessor.<clinit>(JavaProcessor.java:112)
    ... 40 more
```
