### ISSUE TITLE
Error: Attempt to modify PSI for non-committed Document

### ISSUE THREAD

**Issue by tabbed** [dubreuia/intellij-plugin-save-actions#40]
Opened the Maven Projects "Tab" and then this error came up:

Stacktrace:
`
Attempt to modify PSI for non-committed Document!
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:325)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:146)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
    at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:660)
    at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:767)
    at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:81)
    at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:544)
    at com.intellij.psi.impl.source.tree.java.ModifierListElement.addInternal(ModifierListElement.java:45)
    at com.intellij.psi.impl.source.PsiModifierListImpl.setModifierProperty(PsiModifierListImpl.java:239)
    at com.intellij.psi.util.PsiUtil.setModifierProperty(PsiUtil.java:1108)
    at com.intellij.codeInspection.localCanBeFinal.LocalCanBeFinal$AcceptSuggested.applyFix(LocalCanBeFinal.java:341)
    at com.intellij.codeInspection.localCanBeFinal.LocalCanBeFinal$AcceptSuggested.applyFix(LocalCanBeFinal.java:325)
    at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction.writeQuickFixes(InspectionProcessor.java:82)
    at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction.run(InspectionProcessor.java:74)
    at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:162)
    at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
    at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:108)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
    at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:103)
    at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:34)
    at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:723)
    at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:82)
    at com.dubreuia.processors.InspectionProcessor$1.run(InspectionProcessor.java:48)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by dubreuia** [comment]
Thanks for that. If that happens often you can deactivate any "quick fix" actions so you can continue using the plugin.

Can you give me your plugin version, idea version and the last lines of your ~/.IntelliJIdea2016.1/system/log/idea.log please I'll check it out

**Comment by tabbed** [comment]
Hi,
I am using

IntelliJ IDEA 2016.1.2
Build #IU-145.971, built on April 29, 2016
JRE: 1.8.0_73-b02 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Plugin-Version: 0.9

Here are the last lines of idea.log:
`2016-05-12 15:33:19,928 [18281484]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobHistoryBean.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:34:48,182 [18369738]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobResult.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:36:51,395 [18492951]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobMonitorImpl.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:36:51,432 [18492988]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobBean.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:36:51,466 [18493022]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobMonitor.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:36:51,493 [18493049]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobHistoryBean.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:37:21,550 [18523106]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobDTO.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:38:31,333 [18592889]   INFO - svn.commandLine.CommandRuntime - Detected warning - svn: warning: W155007: 'C:\work\EKO\eko-Main\eko-business-api\src\main\java\at\itsv\eko\business\dto\async\JobDTO.java' is not a working copy
 
2016-05-12 15:38:31,668 [18593224]   INFO - svn.commandLine.CommandRuntime - Detected warning - svn: warning: W155007: 'C:\work\EKO\eko-Main\eko-business-api\src\main\java\at\itsv\eko\business\dto\async\JobDTO.java' is not a working copy
 
2016-05-12 15:40:59,640 [18741196]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobHistoryBean.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:40:59,672 [18741228]  DEBUG - com.dubreuia.SaveActionManager - Running processors [OptimizeImports (false), ReformatAllText (false), RearrangeCode (false), LocalCanBeFinal (true), Convert2Diamond (false), UnqualifiedFieldAccess (true), SuppressionAnnotation (false), FinalPrivateMethod (false), UnnecessarySemicolon (true), FieldMayBeFinal (false), Compile (false)], file PsiJavaFile:JobFinishedDTO.java, project Project 'C:\work\EKO\eko-Main' eko-Main 
2016-05-12 15:40:59,880 [18741436]  ERROR - pplication.impl.LaterInvocator - Attempt to modify PSI for non-committed Document! 
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:325)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:146)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:709)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:204)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:552)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:210)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.replace(CompositePsiElement.java:212)
	at com.siyeh.ig.PsiReplacementUtil.replaceExpressionAndShorten(PsiReplacementUtil.java:53)
	at com.siyeh.ig.fixes.AddThisQualifierFix.doFix(AddThisQualifierFix.java:79)
	at com.siyeh.ig.InspectionGadgetsFix.applyFix(InspectionGadgetsFix.java:43)
	at com.siyeh.ig.InspectionGadgetsFix.applyFix(InspectionGadgetsFix.java:27)
	at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction.writeQuickFixes(InspectionProcessor.java:82)
	at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction.run(InspectionProcessor.java:74)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:162)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:108)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:103)
	at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:34)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:723)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:82)
	at com.dubreuia.processors.InspectionProcessor$1.run(InspectionProcessor.java:48)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-05-12 15:40:59,882 [18741438]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2016.1.2  Build #IU-145.971.21 
2016-05-12 15:40:59,882 [18741438]  ERROR - pplication.impl.LaterInvocator - JDK: 1.8.0_73 
2016-05-12 15:40:59,882 [18741438]  ERROR - pplication.impl.LaterInvocator - VM: Java HotSpot(TM) 64-Bit Server VM 
2016-05-12 15:40:59,882 [18741438]  ERROR - pplication.impl.LaterInvocator - Vendor: Oracle Corporation 
2016-05-12 15:40:59,882 [18741438]  ERROR - pplication.impl.LaterInvocator - OS: Windows 7 
2016-05-12 15:40:59,883 [18741439]  ERROR - pplication.impl.LaterInvocator - Last Action: ChangesView.AddUnversioned`

**Comment by krasa** [comment]
I would put there
PsiDocumentManager manager = PsiDocumentManager.getInstance(project);
manager.commitDocument(document);

**Comment by dubreuia** [comment]
Duplicate #53
