### ISSUE TITLE
Exception: Cannot create configurable

### ISSUE THREAD

**Issue by arpitp8595** [dubreuia/intellij-plugin-save-actions#432]
**Describe the bug**
I am trying to install plug-in and it is asking me to disable. both versions 2.3.0 and 2.6.0 are having the same issue with my IDE. 

Cannot create configurable

com.intellij.diagnostic.PluginException: Cannot create class com.dubreuia.ui.Configuration (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Save Actions, id=com.dubreuia, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\intellij-plugin-save-actions-2.3.0.jar, version=2.3.0, package=null, isBundled=false), packagePrefix=null, instanceId=91, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:438)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:344)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:43)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:124)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:99)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.findConfigurableProject(SettingsTreeView.java:344)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyRenderer.getTreeCellRendererComponent(SettingsTreeView.java:652)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paintRow(BasicTreeUI.java:1784)
	at com.intellij.util.ui.tree.WideSelectionTreeUI.paintRow(WideSelectionTreeUI.java:316)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyTreeUi.paintRow(SettingsTreeView.java:942)
.
.
.
.

**What triggered the plugin**
Nothing specifically, I tried to install the plugin and it immediately gives me the error.

**Versions**
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Fiserv / Arpit Patel
You have a perpetual fallback license for this version.
Subscription is active until May 31, 2024.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2032M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (231.8109.91)
    com.intellij.kubernetes (231.8770.3)
    com.dubreuia (2.3.0)
    com.dguner.lombok-builder-helper (1.5.0)
    com.jetbrains.jax.ws (231.8109.90)
    com.ifengxue.plugin.jpa-support (2.1.0-RC3)
    com.intellij.bigdatatools (231.9011.1)
    com.haulmont.jpab (2023.2.3-231)

Kotlin: 231-1.8.21-IJ9011.34

**Comment by fishermans** [comment]
This is the stack trace from 2.3.0 which is not compatible with 2023.1.x.

Please provide the stack trace for 2.6.0.

**Comment by arpitp8595** [comment]
My issue seems to be resolved after removing the 2.3.0 and reinstallation of 2.6.0 and restarting the IDE after couple of times. Thanks for the information about the compatibility of version 2023.1.x. We don't need this issue anymore. I am going to close this issue.
Thanks.!
