### ISSUE TITLE
create class file error after install intellij-plugin-save-actions 

### ISSUE THREAD

**Issue by hero710692586** [dubreuia/intellij-plugin-save-actions#52]
install intellij-plugin-save-actions 
if I create new class file, the new file will be generate two package code.
like this: package com.demo;package com.demo;
and I can not save it use 'ctrl + s', can show error dialog.

**Comment by dubreuia** [comment]
I cannot reproduce. You are creating a "java" file not a class file right? What is in the error dialog?

Can you send me the idea.log please? Should be located under ~/.IntelliJIdea2016.2/system/log

**Comment by hero710692586** [comment]
sorry! So long to reply you.
yes, I am creating a "java" file.
The error  dialog  message: Unable to parse template "Class" Error message:0.

**Comment by mwinkelmann** [comment]
I have the same Issue after installing this plugin:

`2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - IntelliJ IDEA 2016.2.1  Build #IU-162.1447.26 
2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - JDK: 1.8.0_76-release 
2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - VM: OpenJDK 64-Bit Server VM 
2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - Vendor: JetBrains s.r.o 
2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - OS: Mac OS X 
2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - Last Action: NewElement 
2016-08-11 09:03:34,753 [ 598158]  ERROR - psi.SingleRootFileViewProvider - Current Command: Creating class bli.bla.blubb.test
 
2016-08-11 09:03:34,753 [ 598158]   INFO - es.ui.CreateFromTemplateDialog - 0 
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.intellij.ide.fileTemplates.JavaCreateFromTemplateHandler.createClassOrInterface(JavaCreateFromTemplateHandler.java:75)
        at com.intellij.ide.fileTemplates.JavaCreateFromTemplateHandler.createFromTemplate(JavaCreateFromTemplateHandler.java:106)
        at com.intellij.ide.fileTemplates.FileTemplateUtil.a(FileTemplateUtil.java:340)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:906)
        at com.intellij.ide.fileTemplates.FileTemplateUtil.b(FileTemplateUtil.java:338)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:122)
`

Also after de-install the plugin in IntelliJ
