### ISSUE TITLE
NoSuchMethodError when rearrange code is activated

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#7]
It seems the rearrange code processor is not shipped with every intellij version (it might come from a plugin).

*Easy workaround*: go in "File > Settings > Save Actions > Rearrange code" and uncheck the option. Your code will still reformat but won't reorder.

```
com.intellij.codeInsight.actions.RearrangeCodeProcessor.<init>(Lcom/intellij/codeInsight/actions/AbstractLayoutCodeProcessor;Lcom/intellij/openapi/util/Condition;)V
java.lang.NoSuchMethodError:
com.intellij.codeInsight.actions.RearrangeCodeProcessor.<init>(Lcom/intellij/codeInsight/actions/AbstractLayoutCodeProcessor;Lcom/intellij/openapi/util/Condition;)V
        at
com.dubreuia.processors.ProcessorFactory.getRearrangeCodeProcessor(ProcessorFactory.java:38)
        at
com.dubreuia.processors.ProcessorFactory.getSaveActionsProcessor(ProcessorFactory.java:21)
        at com.dubreuia.Component$1.beforeDocumentSaving(Component.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at
com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
        at
com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
        at
com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
        at
com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
        at
com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
        at
com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
        at com.sun.proxy.$Proxy20.beforeDocumentSaving(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:128)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:116)
        at com.sun.proxy.$Proxy20.beforeDocumentSaving(Unknown Source)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$4.run(FileDocumentManagerImpl.java:411)
        at
com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:354)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:408)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocument(FileDocumentManagerImpl.java:382)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:303)
        at
com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:282)
        at
com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1452)
        at
com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:26)
        at
com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
        at
com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
        at
com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:513)
        at
com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
        at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
        at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by dubreuia** [comment]
Corrected on master.

**Comment by raphaelfsousa** [comment]
Hi,

I'm still facing the same issue.
Do have any idea on how to fix it (or workaround)?
I'm using the Intellij Ultimate 14.1.1 (141.178), JDK 1.7.0-51 and Save Action plugin version 0.2.

Thanks!

**Comment by AbdElraoufSabri** [comment]
Hi, @raphaelfsousa, the author pointed to that in the top of the issue page
Easy workaround: go in "File > Settings > Save Actions > Rearrange code" and uncheck the option. Your code will still reformat but won't reorder.

**Comment by dubreuia** [comment]
The workaround should work. I pushed the correction, I just need to repackage the plugin and upload it. I'll do that this weekend.

**Comment by dubreuia** [comment]
The new version is being validated at JetBrains. For posterity, the change that broke the processor: https://github.com/JetBrains/intellij-community/commit/8e5bf0aa2eb0c42b90558e4ca0c55526f0ce5fe8
