### ISSUE TITLE
Conflicting component name 'SaveActionSettings': class uk.co.ben_gibson.repositorymapper.Settings.Settings and class com.dubreuia.model.Storage

### ISSUE THREAD

**Issue by markieww** [dubreuia/intellij-plugin-save-actions#70]
```
Conflicting component name 'SaveActionSettings': class uk.co.ben_gibson.repositorymapper.Settings.Settings and class com.dubreuia.model.Storage
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.configurationStore.ComponentStoreImpl.doAddComponent(ComponentStoreImpl.kt:269)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:233)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:238)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:205)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at com.dubreuia.ui.Configuration.<init>(Configuration.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:347)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:273)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:53)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:112)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:93)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:42)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:35)
	at com.intellij.ui.CardLayoutPanel.lambda$selectLater$1(CardLayoutPanel.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by markieww** [comment]
I guess it has been introduced by 
https://github.com/dubreuia/intellij-plugin-save-actions/commit/1c09d697fce2d6fd24edccdcedabd6b0928d4b9f

or it is a side effect of switching from global to project specific settings storage?

**Comment by dubreuia** [comment]
Oh god this is awful, it is a name clash with another plugin : https://github.com/ben-gibson/jetbrains-open-in-git-host/blob/master/src/uk/co/ben_gibson/repositorymapper/Settings/Settings.java

I'll have to change the name of the storage...

Does the plugin still work for you? I don't have a workaround (except deactivating the "Open in Git host" plugin). I'll try to fix that ASAP

**Comment by markiewb** [comment]
It happens when you change a setting. The saveaction settings won't be saved.

I do not why the author of the other plugin chose such a duplicate name? Perhaps he copied code from this plugin?

**Comment by dubreuia** [comment]
No it's just bad luck. Parameter "name" in State annotation.

`@State(name = "SaveActionSettings",
    storages = {@Storage(id = "default", file = StoragePathMacros.PROJECT_CONFIG_DIR + "/settings.xml")}
)`

**Comment by markiewb** [comment]
@dubreuia: Could you fix it?

**Comment by dubreuia** [comment]
No time for now. I think the correction is just to change state name to "com.dubreuia.SaveActionSettings".

**Comment by markiewb** [comment]
@dubreuia: Yes that looks reasonable.

**Comment by markiewb** [comment]
I created a PR for the other plugin - https://github.com/ben-gibson/jetbrains-open-in-git-host/pull/37

**Comment by markiewb** [comment]
@dubreuia Please close this issue! The other conflicting plugin has been fixed. So there is nothing to do here.

**Comment by dubreuia** [comment]
Thanks @markiewb !
