### ISSUE TITLE
Attempt to modify PSI for non-committed Document!

### ISSUE THREAD

**Issue by MartinX3** [dubreuia/intellij-plugin-save-actions#84]
Using v0.15 on IntelliJ Idea Ultimate v2017.1.3

"IDE Fatal Errors"
`Attempt to modify PSI for non-committed Document!
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:353)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:151)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:646)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:753)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:71)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:530)
	at com.intellij.psi.impl.source.tree.java.ModifierListElement.addInternal(ModifierListElement.java:45)
	at com.intellij.psi.impl.source.PsiModifierListImpl.setModifierProperty(PsiModifierListImpl.java:252)
	at com.intellij.psi.util.PsiUtil.setModifierProperty(PsiUtil.java:1107)
	at com.intellij.codeInspection.localCanBeFinal.LocalCanBeFinal$AcceptSuggested.applyFix(LocalCanBeFinal.java:334)
	at com.intellij.codeInspection.localCanBeFinal.LocalCanBeFinal$AcceptSuggested.applyFix(LocalCanBeFinal.java:320)
	at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction$3.run(InspectionProcessor.java:113)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction$2.run(InspectionProcessor.java:104)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.dubreuia.processors.InspectionProcessor$InspectionWriteQuickFixesAction$1.run(InspectionProcessor.java:94)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Saved this file:
`
/**
 * Created by xxxxx on 31.05.17.
 */

/**
 * @author xxxxx
 */
public class StapelAlsEVLPur<T> implements Stapel<T> {
    @Override
    public void insert(final T v) {

    }

    @Override
    public T element() {
        return null;
    }

    @Override
    public T remove() {
        return null;
    }

    @Override
    public int total() {
        return 0;
    }

    @Override
    public boolean isEmpty() {
        return false;
    }
}
`

**Comment by dubreuia** [comment]
Oh god #53 will never go away :(

I'm closing this one and reopening #53
